### ISSUE TITLE
Redundant bytes written

### ISSUE THREAD

**Issue by 0x7CFE** [WanzenBug/bitstream#1]
The following test code fails on version `0.1.1`:

```Rust
let mut output = Vec::new();
{
    let mut writer = BitWriter::new(&mut output);
    writer.write_bit(false).unwrap();
    writer.write_bit(true).unwrap();
}
assert_eq!(output, [0b0100_0000]);
```

In my case one more byte is added with value `0x2`. I noticed that erroneous byte is added upon `BitWriter`'s drop.

If I add `std::mem::forget(writer)` at the end of it's scope all will work as expected.

**Comment by 0x7CFE** [comment]
I've just looked in the `Drop` implementation of `BitWriter`. 

Could you please tell me the meaning of the whole implementation?
```Rust
impl<W> Drop for BitWriter<W> where W: Write {
    fn drop(&mut self) {
        if self.last_fill > 0 {
            let _ = self.inner.write_all(&[self.last_byte, self.last_fill]);
        } else {
            let _ = self.inner.write_all(&[8u8]);
        }
    }
}
```

If I understand correctly, it should write incomplete byte to the stream. Instead I see some bogus values.

**Comment by WanzenBug** [comment]
The extra byte comes from a filler byte that is added so the BitReader can determine how many bits it should read. In your example above, you write 2 Bits, so that the byte should look like 0b0100_0000 (and it does). However, you only ever wrote the first 2 bits, so on drop it adds 0x2 so the reader can know that the only 2 of the bits in 0b0100_000 are actual "data". 

I guess I could make this behavior configurable, if you need it

**Comment by 0x7CFE** [comment]
Got it, thank you. I realized it a minute before reading your comment. 

Still I think it is very strange contract. I'm expecting writer to, well, write bits packed in bytes. I use `BitWriter` to fill some fields in the raw binary file with already established format.

Previously I expected that it will write remaining byte with all extra bits set to zero. I think it's users responsibility to manage lengths.

I would really be happy if this behaviour would be configurable.

**Comment by WanzenBug** [comment]
I just pushed a new version `0.2.0` that defaults to not writing extra bytes. Your code example above now passes, so I'm settings this issue to resolved.

**Comment by 0x7CFE** [comment]
Thank you!
